baseURL = "/"
languageCode = "en-us"
summaryLength = "10"
theme = "kross-hugo"
title = "Abdul Muthalif - UNP Candidate"
[[menu.main]]
URL = "about"
name = "About"
weight = 2
[[menu.main]]
URL = "blog"
name = "Blog"
weight = 3
[[menu.main]]
URL = "portfolio"
name = "Portfolio"
weight = 4
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 5
[params]
address = ""
author = ""
copyright = ""
description = "This is meta description"
email = "contact@abdulmuthalif.com"
google_analitycs_id = ""
home = "Home"
logo = "images/logo.png"
phone = "+94"
theme_color = "#22A11D"
[params.contact]
enable = true
form_action = "#"
[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
URL = "plugins/slick/slick.css"
[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
URL = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
URL = "plugins/slick/slick.min.js"
[[params.plugins.js]]
URL = "plugins/shuffle/shuffle.min.js"
[params.preloader]
enable = true
preloader = ""
[[params.social]]
URL = "https://www.youtube.com/channel/UCHrdBkCsIIAoKS0YkG08r4w"
icon = "ti-youtube"
[[params.social]]
URL = "https://facebook.com/mtamuthalif"
icon = "ti-facebook"
[[params.social]]
URL = "https://www.instagram.com/abdulmuthalif_/"
icon = "ti-instagram"
